language: java
sudo: false # faster builds

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

branches:
  only:
    - master
    - feature/ci

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V