# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test and Build JMeter gRPC Request

on: [push, pull_request]

jobs:
  scan-code:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [java]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
    - name: Pre-commit update
      run: |
        env
        git version
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: adopt
    - name: Set up dependencies
      run: |
        mvn clean install -Dmaven.test.skip=true
        sudo apt-get update
        sudo apt-get -y install xvfb
    - name: Check cacert
      run: |
        ls -la
        printf "changeit" |  keytool -list -v -keystore dist/cert/cacertslocal
      if: always()
    - name: Run unit test
      run: |
        nohup Xvfb :99 > /dev/null 2>&1 &
        export DISPLAY=:99
        mvn test -Djavax.net.ssl.trustStore=dist/cert/cacertslocal -Djavax.net.ssl.trustStorePassword=changeit
    - name: Verify Dummy Log
      run: |
        cat grpc-dummy-server.log
    - name: Update code coverage to codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        cd target/site
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
  build-plugin:
    runs-on: ubuntu-latest
    needs: [run-test]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: adopt
    - name: Build gRPC Plugin
      run: |
        mvn clean install package -Dmaven.test.skip=true
    - uses: actions/upload-artifact@v2
      with:
        name: gRPC-JMeter-plugin
        path: |
          ./target/jmeter-grpc-request.jar
          README.md
